# Generated by Django 4.2.6 on 2023-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_a_name', models.CharField(max_length=100)),
                ('device_a_interface', models.CharField(max_length=50)),
                ('device_a_ip', models.GenericIPAddressField()),
                ('device_b_name', models.CharField(max_length=100)),
                ('device_b_interface', models.CharField(max_length=50)),
                ('device_b_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
